Appointment/Appointment/Controllers/ReminderController.cs
using Appointment.Business.Models;
using Appointment.ViewModel.Enums;
using Appointment.ViewModel.Models;
using Kendo.Mvc.Extensions;
using System;
using System.Collections.Generic;
using System.DirectoryServices.AccountManagement;
using System.Reflection.PortableExecutable;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using System.Linq;
using Appointment.Business.ActiveDirectory;

//test
namespace Appointment.Controllers
{
    [UserRoleAuthorize(Roles = "Admin")]
    public class ReminderController : BaseController
    {
               /// <summary>
        /// Index method displays data from DB into a grid
        /// </summary>
        /// <returns>the reminders in the DB</returns>
        public ActionResult Index(int? id)
        {

            return View(ReminderService.Read());
        }







        /// <summary>
        /// function called by index view when click edit on grid 
        /// </summary>
        /// <param name="id"> reminder id </param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Update(int id)
        {

            var type = ReminderService.GetType(id);
            if (type == LookupService.GetLookupIdByCode((int)Lookups.employee))
            {
                EmployeeRemindersViewModel obj = new EmployeeRemindersViewModel();
                obj = ReminderService.EmployeeRemindersGetByID(id);
                obj.Positions = ReminderService.GetPositions();
                obj.Employees = ReminderService.GetEmployees();
                obj.Groups = ReminderService.GetGroups();
                return View("EmployeeReminderUpdate", obj);
            }
            else
            {
                GeneralRemindersViewModel obj = new GeneralRemindersViewModel();
                obj = ReminderService.generalRemindersGetByID(id);
                obj.Groups = ReminderService.GetGroups();
                return View("GeneralReminderUpdate", obj);
            }
        }



        /// <summary>
        /// method gets the changes of reminder that user made then save it in DB
        /// </summary>
        /// <param name="reminder">gets the data from the model</param>
        /// <returns>all reminders in DB after the change is done</returns>
        [HttpPost]
        public ActionResult EmployeeReminderUpdate(EmployeeRemindersViewModel reminder, HttpPostedFileBase image1)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    reminder.ModifyOn = DateTime.Now;
                    reminder.ModifyBy = 1;
                    if (image1 != null)
                    {
                        string imgname = DateTime.Now.ToString("yyyyMMddhhmmss") + image1.FileName;
                    
                    
                       string ImagePathphiscal = AppDomain.CurrentDomain.BaseDirectory + "img\\" + imgname;
                        image1.SaveAs(ImagePathphiscal);
                        reminder.ImagePath = "~/img/" + imgname;
                    }

                    //The model is valid - update the reminder and redisplay the grid.
                    ReminderService.EmployeeReminderUpdate(reminder, image1);

                    //GridRouteValues() is an extension method which returns the 
                    //route values defining the grid state - current page, sort expression, filter etc.
                    RouteValueDictionary routeValues = this.GridRouteValues();

                    return View("Index", ReminderService.Read());
                }
                else
                {
                    List<string> Errors = new List<string>();

                    foreach (ModelState modelState in ViewData.ModelState.Values)
                    {
                        foreach (ModelError error in modelState.Errors)
                        {
                            Errors.Add(error.ErrorMessage);
                        }
                    }
                }

            }
            catch (Exception ex)
            {
                throw ex;
            }
            //The model is invalid - render the current view to show any validation errors
            return View();
        }








        /// <summary>
        /// general reminder edit method
        /// </summary>
        /// <param name="reminder">gets the changes of the reminder to save it</param>
        /// <returns>index view</returns>
        public ActionResult GeneralReminderUpdate(GeneralRemindersViewModel reminder)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    reminder.ModifyOn = DateTime.Now;
                    reminder.ModifyBy = 1;


                    //The model is valid - update the reminder and redisplay the grid.
                    ReminderService.GeneralReminderUpdate(reminder);

                    //GridRouteValues() is an extension method which returns the 
                    //route values defining the grid state - current page, sort expression, filter etc.

                    return RedirectToAction("Index", ReminderService.Read());
                }
                else
                {
                    List<string> Errors = new List<string>();

                    foreach (ModelState modelState in ViewData.ModelState.Values)
                    {
                        foreach (ModelError error in modelState.Errors)
                        {
                            Errors.Add(error.ErrorMessage);
                        }
                    }
                }

            }
            catch (Exception ex)
            {

                throw ex;
            }
            //The model is invalid - render the current view to show any validation errors
            return View();
        }








        /// <summary>
        /// method called when new general reminder is clicked
        /// </summary>
        /// <returns>view</returns>
        [HttpGet]
        public ActionResult NewGeneralReminder()
        {
            GeneralRemindersViewModel obj = new GeneralRemindersViewModel();
            obj.Groups = ReminderService.GetGroups();


            return View(obj);
        }


        /// <summary>
        /// creates a new reminder of type general
        /// </summary>
        /// <param name="reminder">new reminders data</param>
        /// <returns>view</returns>
        [HttpPost]
        public ActionResult NewGeneralReminder(GeneralRemindersViewModel reminder)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    //The model is valid - insert the reminder and redisplay the grid.

                    reminder.CreatedOn = DateTime.Now;
                    reminder.CreatedBy = 1;

                    ReminderService.Create(reminder);

                    //GridRouteValues() is an extension method which returns the 
                    //route values defining the grid state - current page, sort expression, filter etc.
                    RouteValueDictionary routeValues = this.GridRouteValues();

                    return RedirectToAction("Index", routeValues);
                }

                //The model is invalid - render the current view to show any validation errors
                return View();
            }
            catch (Exception ex)
            {

                throw ex;
            }
            
        }








        /// <summary>
        /// method called when new employee reminder button is clicked
        /// </summary>
        /// <returns>view</returns>
        [HttpGet]
        public ActionResult NewEmployeeReminder()
        {
            //TempData["isvalid"] = true;
            EmployeeRemindersViewModel obj = new EmployeeRemindersViewModel();
            obj.Positions = ReminderService.GetPositions();
            obj.Employees = ReminderService.GetEmployees();
            obj.Groups = ReminderService.GetGroups();

            return View(obj);
        }



        /// <summary>
        /// creates new reminder of type employee
        /// </summary>
        /// <param name="reminder">new reminders data</param>
        /// <returns>view</returns>
        [HttpPost]
        public ActionResult NewEmployeeReminder(EmployeeRemindersViewModel reminder)
        {
            List<string> Errors = new List<string>();

            bool isvalid = false;
            if (ModelState.IsValid)
            {
                
                reminder.CreatedOn = DateTime.Now;
                reminder.CreatedBy = 1;
                ReminderService.Create(reminder);


                //GridRouteValues() is an extension method which returns the 
                //route values defining the grid state - current page, sort expression, filter etc.
                RouteValueDictionary routeValues = this.GridRouteValues();

                return RedirectToAction("Index", routeValues);
            }
            else
            {

                foreach (ModelState modelState in ViewData.ModelState.Values)
                {
                    foreach (ModelError error in modelState.Errors)
                    {
                        Errors.Add(error.ErrorMessage);
                    }
                }
            }
            //TempData["isvalid"] = isvalid;

            return View();
        }








        /// <summary>
        /// show reminder details of type employee 
        /// </summary>
        /// <param name="id">selected reminder id</param>
        /// <returns>method employeeremindergetbyid call</returns>
        public ViewResult Details(int id)
        {
            var type = ReminderService.GetType(id);
            if (type == LookupService.GetLookupIdByCode((int)Lookups.employee))
            {
                EmployeeRemindersViewModel obj = new EmployeeRemindersViewModel();
                obj = ReminderService.EmployeeRemindersGetByID(id);

Appointment/Appointment/Views/Reminder/Details.cshtml
@model Appointment.ViewModel.Models.EmployeeRemindersViewModel

@{
    ViewBag.Title = "Details";
}
<br />
<br />
<h2>Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <br />
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <br />
        <dt>
            @Html.DisplayName("Birth Date")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthDate)
        </dd>
        <br />
        <dt>
            @Html.DisplayName("Starting Date")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <br />
        <dt>
            @Html.DisplayName("Position")
        </dt>

        <dd>
            @Html.DisplayFor(m => m.Position)
        </dd>
        <br />
        <dt>
            @Html.DisplayName("Create Date")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>
        <br />
        <dt>
            @Html.DisplayName("Modify Date")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifyOn)
        </dd>
        <br />
        <dt>
            @Html.DisplayName("Type")
        </dt>

        <dd>
            @Html.Label("Employee Reminder")
        </dd>
        <br />
        <dt>
            @Html.DisplayName("Image")
        </dt>

        <dd>
            @if (Model.ImagePath != null)
            {
                <img src="@Url.Content(Model.ImagePath)"  height="100px" width="100px"/>
            }

        </dd>
        <br />
        <dt>
            @Html.DisplayName("Active")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

    </dl>
</div>
<p>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="button" value="Back" class="btn btn-default" onclick="location.href='@Url.Action("Index", "Reminder")'" />
        </div>
    </div>
</p>

Appointment/Appointment/Views/Reminder/EmployeeReminderUpdate.cshtml
@model Appointment.ViewModel.Models.EmployeeRemindersViewModel

@{
    ViewBag.Title = "Employee Reminder Update";
    Layout = "~/Views/Shared/_Layout.cshtml";


}

<br />
<br />
<div>
    <h2>Employee Reminder Edit</h2>

    @using (Html.BeginForm("EmployeeReminderUpdate", "Reminder", FormMethod.Post, new { enctype = "multipart/form-data" }))

    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">


            <hr />
            @Html.HiddenFor(model => model.ID, new { htmlAttributes = new { @Id = "ReminderID" } })

            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.BirthDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.EditorFor(model => model.BirthDate, new { htmlAttributes = new { @Id = "Birth", @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @Id = "Start", @class = "form-control", value = "{0:dd/MM/yyyy}" } })
                    @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.PositionID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.DropDownListFor(m => m.PositionID, new SelectList(Model.Positions, "Value", "Text"), new { @class = "form-control", @Id = "Position" })
                    @Html.ValidationMessageFor(m => m.PositionID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.EmployeeID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.DropDownListFor(m => m.EmployeeID, new SelectList(Model.Employees, "Value", "Text"), new { @Id = "employee" })
                    @Html.ValidationMessageFor(m => m.EmployeeID, "", new { @class = "text-danger" })

                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @ReadOnly = "ReadOnly" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    @*<label id="EmailError" style="display:none;color:red;">This Email is already used !</label>*@
                </div>
            </div>

            <div class="form-group">
                @Html.Label("Groups", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.ListBoxFor(m => m.SelectedGroupsID, new SelectList(Model.Groups, "Value", "Text"), new { id = "Group", multiple = "true" })
                    @Html.ValidationMessageFor(m => m.SelectedGroupsID, "", new { @class = "text-danger" })
                    @*<lable id="lblGroupValidation" style="color:red;font-weight:bold;display:none;"></lable><br /><br />*@
                </div>
            </div>

            <div class="form-group">
                @Html.Label("Image", htmlAttributes: new { @class = "control-label col-md-2" })
                @*<div class="col-md-10">*@
                <div class="col-md-5">
                    <input type="file" name="image1" id="image1" class="form-control" />
                    @if (Model.ImagePath != null)
                    {
                        <img id="myImg" src="@Url.Content(Model.ImagePath)" height="40px" width="40px" />

                    }
                </div>
                @*</div>*@
            </div>

            <div class="form-group">
                @Html.Label("Active", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>



            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Edit" class="btn btn-default" id="btnSubmit" />
                    <input type="button" value="Back" class="btn btn-default" onclick="location.href='@Url.Action("Index", "Reminder")'" />
                </div>
            </div>
        </div>
    }
</div>


<link href="https://kendo.cdn.telerik.com/2019.2.619/styles/kendo.common.min.css" rel="stylesheet" type="text/css" />
<link href="https://kendo.cdn.telerik.com/2019.2.619/styles/kendo.default.min.css" rel="stylesheet" type="text/css" />
<script src="https://kendo.cdn.telerik.com/2019.2.619/js/jquery.min.js"></script>
<script src="https://kendo.cdn.telerik.com/2019.2.619/js/kendo.all.min.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

<link href="~/Scripts/bootstrap-multiselect.css" rel="stylesheet" />
<script src="~/Scripts/bootstrap-multiselect.js"></script>


<script>
    $(document).ready(function () {
        $('#Position').multiselect({
            includeSelectAllOption: false,
            enableCaseInsensitiveFiltering: true,
            enableFiltering: true,
            multiselect: false,
            maxHeight: 200
        });


        $('#employee').multiselect({
            includeSelectAllOption: false,
            enableCaseInsensitiveFiltering: true,
            enableFiltering: true,
            multiselect: false,
            maxHeight: 200
        });


        $('#Group').multiselect({
            includeSelectAllOption: true,
            enableCaseInsensitiveFiltering: true,
            enableFiltering: true,
            maxHeight: 200
        });


        var presentDate = new Date();
        var varDate = new Date((new Date().getFullYear() - 18), 0, 1);
            $("#Birth").kendoDatePicker({
                max: varDate
        });

        $("#Start").kendoDatePicker({
            min: presentDate,
        });
        var nowDate = Date.now.toString();
        //'GlobalExposures / Replicate ? q = ' + $("#HdnReplicateID").val()+ "&ContractStatusID=" + $("#ContractStatusID").val();
        $('#employee').change(function () {
            $("#EmailError").hide();
            $('#btnSubmit').removeAttr('disabled');
            var EmploeeID = $('#employee').val();

            $.ajax({
                url: '@Url.Action("FetchEmail", "Reminder")/?ID=' + EmploeeID + "&ReminderID=" + @Model.ID ,
                type: "GET",
                cache: false,
                async: false,
                includeSelectAllOption: true,
                enableCaseInsensitiveFiltering: true,
                enableFiltering: true,
                //data: { ID: EmploeeID },
                datatype: "json",
                success: function (response) {
                    $('#Email').val(response.Email);
                    var lblEmailValidation = $("#EmailError");
                    var btnSubmit = $('#btnSubmit');
                    debugger;
                    if (response.CanBeUsed) {
                        lblEmailValidation.hide();
                        btnSubmit.removeAttr('disabled');
                    } else {
                        lblEmailValidation.show();
                        btnSubmit.attr('disabled', 'true');
                    }
                },
                error: function (error) {
                    debugger;
                    alert(error);
                }
            });
        });

        $("form").submit(function () {
        debugger;
        $('button[type=button], input[type=button]').prop('disabled', true);
        $('button[type=submit], input[type=submit]').prop('disabled', true);
        $("form").each(function () { $.data($(this)[0], 'validator', false); });
        var fom = $("form");
        $.validator.unobtrusive.parse(fom);
        if ($("form").valid()) {
            //fillFieldsForSubmit();
        }
        else {
            $("form").valid();
            $("form").each(function () { $.data($(this)[0], 'validator', false); });
            $.validator.unobtrusive.parse("form");
            $('button[type=button], input[type=button]').removeAttr('disabled');
            $('button[type=submit], input[type=submit]').removeAttr('disabled');
        }
    });

    });



    //Image Uploader
    $(function () {
        debugger;
        $(":file").change(function () {
            if (this.files && this.files[0]) {
                var reader = new FileReader();

                reader.onload = imageIsLoaded;
                reader.readAsDataURL(this.files[0]);
            }
        });
    });

    function imageIsLoaded(e) {
        $('#myImg').attr('src', e.target.result);
    };


//    saving_record = 0; //set variable to show if form is in submission
//$(document).ready(function () {
//    $('#form').on('submit', function (e) {
//        if (saving_record === 0) { //If not submitted yet, submit form
//            saving_record = 1; //Set variable to show form is in submission
//            $.ajax({
//                success: function (data) {
//                    saving_record = 0; //Reset variable to allow record update
//                },
//                error: function (data) {
//                    saving_record = 0; //Reset variable to allow record update in case of error
//                }
//            })
//        }
//    });
    


</script>

Appointment/Appointment/Views/Reminder/GeneralDetails.cshtml
@model Appointment.ViewModel.Models.GeneralRemindersViewModel

@{
    ViewBag.Title = "GeneralDetails";
}
<br />
<br />
<h2>Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <br />
        <dt>
            @Html.DisplayName("Starting Date")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <br />
        <dt>
            @Html.DisplayName("End Date")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <br />
        <dt>
            @Html.DisplayName("Description")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BreifDescription)
        </dd>
        <br />
        <dt>
            @Html.DisplayNameFor(model => model.Time)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TimeForDisplay)
        </dd>
        <br />
        

        <dt>
            @Html.DisplayName("Groups")
        </dt>
        <dd>
            @foreach (var group in Model.SelectedGroups)
            {
            <p>@Html.DisplayFor(model => group)  </p>
            }
        </dd>
        <br />
        <dt>
            @Html.DisplayName("Creation Date")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>
        <br />
        <dt>
            @Html.DisplayName("Modify Date")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifyOn)
        </dd>
        <br />
        <dt>
            @Html.DisplayName("Type")
        </dt>

        <dd>
            @Html.Label("General Reminder")
        </dd>
        <br />
        <dt>
            @Html.DisplayName("Active")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

    </dl>
</div>
<p>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="button" value="Back" class="btn btn-default" onclick="location.href='@Url.Action("Index", "Reminder")'" />
        </div>
    </div>
</p>

<style>
    p {
        display: inline;
    }
</style>

Appointment/Appointment/Views/Reminder/Index.cshtml
@model IEnumerable<Appointment.ViewModel.Models.RemindersViewModel>

@{
    ViewBag.Title = "All reminders";
    Layout = "~/Views/Shared/_Layout.cshtml";

}


<br />
<br />
<br />
<br />
<div class="row">
    <div class="col-md-12">
        @(Html.Kendo().Grid(Model)
              .Name("Grid")

              .Columns(columns =>
              {

                  columns.Bound(p => p.Name).Filterable(ftb => ftb.Cell(cell => cell.Operator("contains").SuggestionOperator(FilterType.Contains).Delay(600000)));
                  columns.Bound(p => p.StartDate).Format("{0:dd/MM/yyyy}");
                  columns.Bound(p => p.EndDate).Format("{0:dd/MM/yyyy}");
                  columns.Bound(p => p.TypeName).Filterable(ftb => ftb.Cell(cell => cell.Operator("contains").SuggestionOperator(FilterType.Contains).Delay(600000)));
                  columns.Bound(p => p.IsActive).Template(P => P.IsActive.HasValue ? (P.IsActive.Value ? "Active" : "Inactive") : "Inactive").ToString();


                  columns.Command(command =>
                  {
                      command.Custom("Details").Action("Details", "Reminder").HtmlAttributes(new { id = "viewItem", title = "View", style = "width:30px;", value = "View Details" });
                      command.Custom("Edit").Action("Update", "Reminder").HtmlAttributes(new { id = "editItem", title = "Edit", value = "View Details" });
                  }).Width(250);
              })
                .ToolBar(toolbar => toolbar.Custom()
                .Text("New Employee Reminder")
                .Action("NewEmployeeReminder", "Reminder"))
                .ToolBar(toolbar => toolbar.Custom()
                .Text("New General Reminder")
                .Action("NewGeneralReminder", "Reminder"))
              .Editable(editable => editable.Enabled(false).Mode(GridEditMode.InCell))
              .Pageable(pageable => pageable
                       .Refresh(true)
                       .PageSizes(true)
                       .ButtonCount(5))
              .Sortable()
              .Navigatable()
              .Scrollable()
              .Selectable(selectable => selectable.Enabled(true).Mode(GridSelectionMode.Single).Type(GridSelectionType.Row))
              .Filterable(filterable => filterable.Mode(GridFilterMode.Row))
              .Filterable(filterable => filterable.Messages(m => m.IsFalse("Inactive"))
              .Messages(m => m.IsTrue("Acitve")))
              .HtmlAttributes(new { style = "height:400px;" })
              .DataSource(dataSource => dataSource
                  .Server()
                  .PageSize(20)
                  .Model(model => model.Id(p => p.ID))
                  .Read("Index", "Reminder")
              )
        )
    </div>

</div>

<style>
    .k-grid .k-state-selected {
        background: #1cacff;
        color: #000000;
    }

    .k-grid tr.k-state-selected:hover {
        background-color: #c5f1ff;
    }
</style>


<script type="text/javascript">

    $(document).ready(function () {
        $("form.k-edit-form").kendoValidator();

        

    });

</script>